branches:
  only:
  - master
language: python
python:
- '3.4'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}"
  == "false" ]; then pip install pygithub; pip install pygithub3; fi
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py
env:
  global:
  - secure: cdxkn5cAx+s1C9Ne5m+odEhde1uuSg6XGMDgepN4DwSAJwtMnUv3ZmDebd5YJC1raZJdep+n09Cj0GoTNICQRkco50DxHKHYNad41wetY0tn0cs9gmPYzyFE5q4vuWiQ47dlGhQQ7IJDyX0nU++gG5E50/PhlZfebdedGSprN/4=
notifications:
  slack:
    secure: xjPH9X7VXvaIBL3zLfgCxCc562n+8MzBeC6MgefNbVlcIAYQbFBG7Y50+swYCpqGZcQZdFVCBGOwhCjj55HxB2Phv6fKxheTg7YcpeUO3aTuQ212n0PF6ePtWHu0qXOO+WAxiRmD9/jBDbdsCJk9bw2ShR2ecQqfP3T1kkMRA/cD1wSs66VILOfrobJ4Cvqdfiajhq8lNRbqmWmEX0aB/54L2K9hnaZSiUSO+Cx18vfD3d+r5Zyi2Jlx54hN99+o35TFBhQWve9havZURTJXj20p1jM+uJnaqsEwGdyr1HTQABs6Vtf3pRDy6Blz029DwKCistrkTMq3V9Gg+wBMBZbcYyCcXzA6cbxB3NJgM/tj4hVLrGh4Nkpg8JU1uRNawcO0y0oV4aPyKsUpnX8+1i/kzWmzJkHkWuKcobNvRTxFu6CtE3cjX9cq1+S7q+So/O9dXDpStfyDsR/PRHEfgdJCoOuMu/0LL8tN2g9rR6nCiOWtBy4tQq3fo33xfVxS3Ufb6QFCZOfdeDECFUj5h7ZCU82gDJ07qVduCk7PVH6yG7peHMf3O4OQcgSfnSW4KgKfb2sEtZuYa6s2xR7mektz6h2mjl72n/3EvJ78wFO8IuUH4qNU2r7Ro/jazgzCwRx2dgp34/ZqXWvSQZ74oPLvmq5nXvGgDo849o1oSWs=
    on_success: change
